emit:
  - "@typespec/openapi3"
  - "@azure-tools/typespec-ts"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/schema"
    openapi-versions:
      - 3.1.0
  "@azure-tools/typespec-ts":
    package-dir: "keyvault-secrets"
    generate-metadata: true
    src-folder: "src/generated"
    experimental-extensible-enums: true
    is-modular-library: true
    package-details:
      name: "@azure/keyvault-secrets"
      description: "Azure Key Vault Secrets"
    flavor: azure
